### ISSUE TITLE
improve contributing.md file

### ISSUE THREAD

**Issue by Nirbhayparmar** [Nirbhayparmar/gradientiser-BgGenerator#11]
**Describe the bug**
Improve the contributing.md file

**Expected behavior**
This project has contributing.md file but it just forward devs towards the tutorials, we need to have step by step guide from forking repo till making pull request, if any body interested can work on this.

**Comment by georgioupanayiotis** [comment]
@Nirbhayparmar can you please assign this to me?

**Comment by bloodmonk7** [comment]
I would love to contribute in this one. Can you please assign this to me?

**Comment by Nirbhayparmar** [comment]
Yes assigning this issue to you. Happy hacktoberfest...

**Comment by georgioupanayiotis** [comment]
@Nirbhayparmar created the PR here https://github.com/Nirbhayparmar/gradientiser-BgGenerator/pull/29

it would be very helpful if you can please review it as soon as possible and merge it or label it as "hacktoberfest-accepted"

**Comment by Nirbhayparmar** [comment]
Thank you everyone who helped to improve contributing.md file.

**Comment by georgioupanayiotis** [comment]
@Nirbhayparmar can you please add label `hacktoberfest-accepted` 
in order to go though my submission!
