### ISSUE TITLE
[BUG] Radio buttons don't work

### ISSUE THREAD

**Issue by Dun-sin** [Nirbhayparmar/gradientiser-BgGenerator#13]
**Describe the bug**
The radio buttons for the gradient don't work

**To Reproduce**
Click on the radio buttons

**Expected behavior**
It should update the background color linear direction

**Screenshots**
![image](https://user-images.githubusercontent.com/78784850/193198246-70f2e8a4-1ec9-4a3d-bce8-859d290edce4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by Nirbhayparmar** [comment]
sorry @Dun-sin, this issue is given previously to my friend earlier, so you can work on other issue.

**Comment by Dun-sin** [comment]
I created the issue lol, but okay
