### ISSUE TITLE
The gradient direction is not random on load

### ISSUE THREAD

**Issue by Semako123** [Nirbhayparmar/gradientiser-BgGenerator#16]
**Describe the bug**
The gradient's direction is not random on load 

**To Reproduce**
1. Reload the page

**Expected behavior**
Generate a random gradient with a random direction

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Browser Firefox

**Comment by Nirbhayparmar** [comment]
Thank you semako123 for solving this issue.
