### ISSUE TITLE
Bug : Improve the visiblity of the text on the screen

### ISSUE THREAD

**Issue by starlightknown** [Nirbhayparmar/gradientiser-BgGenerator#3]
The gradient work is great but the text is in black, if you change the gradient to some dark colours the text is not visible much. I'd suggest to add the text in some code block or out line it so that it pops up more

**Comment by Nirbhayparmar** [comment]
Thank you for your suggestions. I will surely work on this.

**Comment by Jonniie** [comment]
I'll recommend a background color for the areas containing texts to prevent them from being affected by the gradient generated. If you agree with this, then I'll be glad to take it on

**Comment by Nirbhayparmar** [comment]
like a separate container having fixed background color right? I think first you can work on a separate branch, so me how it is looking then I can merge it. I am assigning this issue to you. Happy Hacking....

**Comment by Jonniie** [comment]
@Nirbhayparmar kindly review my PR
