### ISSUE TITLE
Add copy button

### ISSUE THREAD

**Issue by Keith-Web3** [Nirbhayparmar/gradientiser-BgGenerator#30]
**Is your feature request related to a problem? Please describe.**
It's stressful having to select the text containing the color before copying manually. I feel it would improve the user experience to add a button which copies the color immediately without having to select it.

**Describe the solution you'd like**
A small button containing the common copy logo. The button will be placed at the top right of the color text container.

**Describe alternatives you've considered**
I haven't considered any alternative solutions to this but an additional feature I would love to include in the project is a section which allows the user to choose what format of color to get as an output e.g rgb, hex, hsl e.t.c

**Additional context**
I haven't worked on the feature yet but I'll get to it now

**Comment by Nirbhayparmar** [comment]
This issue is solved by PR #31
