### ISSUE TITLE
GitHub Icon overlapping

### ISSUE THREAD

**Issue by psb27** [Nirbhayparmar/gradientiser-BgGenerator#32]
**Describe the bug**
The GitHub Icon overlaps the CSS code generated by the website in full-screen mode. Need to make it responsive.
![gradientiser-issue](https://user-images.githubusercontent.com/74458002/193759936-deb893ad-ffbe-4fea-93e0-a15f49c764b9.JPG)

**Comment by Nirbhayparmar** [comment]
PR #31 solved this issue.
