### ISSUE TITLE
fav-icon /logo for your site to make it look more proffessional

### ISSUE THREAD

**Issue by coderboy-yash** [Nirbhayparmar/gradientiser-BgGenerator#36]
i want to add a fav-icon / logo for your site to make it look like a proffessional site rather than just a project

**Comment by coderboy-yash** [comment]
please assign me this issue raised by me under the #hacktoberfest label.

**Comment by Nirbhayparmar** [comment]
Okay, go with it.

**Comment by coderboy-yash** [comment]
I have added the fav-icon to your site.
I also send a PR to you please merge my PR.

**Comment by coderboy-yash** [comment]
please don't forget to add the hacktoberfest label

**Comment by Nirbhayparmar** [comment]
Solved by pr #39
